-- Rename `fan_out_cursor` to `routing_cursor`.
--
-- The platform had two names for one thing: the component is the ROUTER, and
-- what it did was called "fan-out". Every glossary carried both, and the state
-- newcomers hit most - an event that routed successfully and reached nobody -
-- had to be explained as "the fan-out completed and produced no deliveries".
-- One vocabulary now: the router routes, and this is where it got to.
--
-- DEPLOY ORDERING MATTERS. The data plane reads this column in hand-written
-- SQL (internal/router/store.go), so the old binary knows only `fan_out_cursor`
-- and the new one knows only `routing_cursor`. Run this migration and then
-- restart the data plane. A router running against the other name fails its
-- claim query and parks nothing - it simply stops draining the outbox, which is
-- recoverable but looks like an outage.
--
-- Data is preserved: RENAME COLUMN keeps every value, so a row parked halfway
-- through a wide routing still resumes from where it stopped rather than
-- re-walking subscriptions that already have delivery rows.
--
-- IF EXISTS / IF NOT EXISTS is not used here on purpose. Prisma records this
-- migration once; a silent no-op would let a database that never had the
-- column, or already has the new one, pass as migrated when it is neither.
ALTER TABLE "event_outbox"
  RENAME COLUMN "fan_out_cursor" TO "routing_cursor";
