-- ---------------------------------------------------------------------------
-- delivery_attempts.request_payload — the body THIS attempt put on the wire.
--
-- WHAT IT IS, AND WHAT IT IS NOT.
--
-- The table already records everything else about one attempt: the headers we
-- sent, the status and headers and body we got back, how long it took. The
-- request body was the one part of "what did we send" that had to be read from
-- another table. This column keeps it beside the rest.
--
-- It is EVIDENCE, not the system of record. The authoritative bytes are
-- `events.payload_raw` (or the object named by `events.payload_location` when
-- the event was offloaded), they are hashed into `events.payload_hash`, and the
-- worker verifies what it sends against that hash before it signs anything.
-- This column must never become the only copy of anything, for two reasons:
--
--   1. It is BOUNDED (below), so for a large body it holds a prefix.
--   2. It is pruned FIRST. Retention reclaims attempt detail at
--      DefaultAttemptAge (60 days) and the delivery summary only at
--      DefaultDeliveryAge (90) — see services/data-plane/internal/retention.
--
-- A signature investigation therefore belongs on `GET /events/:id/payload`,
-- which serves the exact bytes. This column answers the narrower question an
-- operator actually asks of a single row: "what did attempt 3 send?"
--
-- WHY TEXT AND NOT JSONB.
--
-- The same two reasons `response_body` is TEXT, and both have already bitten
-- this table:
--
--   - `jsonb` rejects \u0000, and a payload is arbitrary bytes the publisher
--     chose. A NUL in a body must not be able to fail the INSERT that records
--     the attempt — losing the ledger row is far worse than losing the bytes.
--   - A bounded copy of a JSON document is, in general, not JSON: the cut lands
--     mid-string or mid-object. `jsonb` would reject every truncated row.
--
-- The worker strips NULs and repairs invalid UTF-8 before writing (see
-- storableText in internal/worker/deliver.go), so the column holds text that a
-- client can render, and a truncated value is marked `…[truncated]` so nobody
-- debugs a JSON parse error against a prefix.
--
-- WHY BOUNDED, AND AT WHAT.
--
-- MAX_STORED_REQUEST_PAYLOAD_BYTES, default 4 KiB. Unbounded, this column would
-- be the largest thing in the ledger by an order of magnitude: PAYLOAD_MAX_BYTES
-- is 1 MiB, the default retry budget is 8 attempts, and every delivery of one
-- event carries its own attempt chain — so one 1 MiB event to 10 subscribers
-- could write 80 MiB of identical prefixes for bytes already stored once on
-- `events`. A response body is unique information per attempt and is capped at
-- 64 KiB even so; a request body is the SAME bytes every attempt (the signature
-- covers `{t}.{raw body}`, so it cannot vary), which is the argument for
-- keeping a short, identifying prefix rather than a full copy.
--
-- NULLABLE, WITH NO DEFAULT, AND NOT BACKFILLED.
--
-- Every attempt written before this migration has no such record, and there is
-- nothing honest to put there: the event's current bytes are not proof of what
-- that attempt sent, and writing them would manufacture evidence. NULL means
-- "no record of the bytes this attempt sent" and covers three real cases:
-- rows older than this column, rows whose detail retention has reclaimed, and
-- attempts where nothing reached the network at all (the payload could not be
-- fetched or verified, or the delivery could not be signed).
--
-- SAFE ON A POPULATED TABLE. Adding a NULLABLE column with no default is a
-- catalogue-only change on PostgreSQL 11+: no rewrite, and ACCESS EXCLUSIVE
-- held only for the catalogue update. `delivery_attempts` is the highest-volume
-- table in the system, so on a large installation run the statement by hand
-- first with
--
--     SET lock_timeout = '5s';
--
-- and let this migration find the column already present and do nothing.
--
-- NO INDEX. The column is never a predicate; nothing searches bodies. Indexing
-- it would be write cost on the hottest insert path for a query nobody issues.
-- ---------------------------------------------------------------------------

ALTER TABLE "delivery_attempts"
    ADD COLUMN IF NOT EXISTS "request_payload" TEXT;
