import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, OpenAPIObject, SwaggerModule } from '@nestjs/swagger';
import { attachErrorResponses } from './openapi-errors';

/**
 * THE one place the OpenAPI document is built.
 *
 * ## Why this exists
 *
 * `main.ts` (which serves `/docs`) and `openapi.ts` (which emits the file the
 * dashboard client and the public documentation site are generated from) each
 * carried their own copy of the `DocumentBuilder` chain, with a comment asking
 * the reader to keep them identical. They did not stay identical in the one way
 * a comment cannot catch: both registered the cookie scheme under
 * `DocumentBuilder`'s DEFAULT name (`cookie`) while every controller declares
 * `@ApiCookieAuth('session')`, so all 50-odd operations referenced a security
 * scheme that did not exist in `components.securitySchemes`. A renderer shows
 * that as an unauthenticated operation; a strict validator rejects the file.
 *
 * Two callers of one function cannot drift. The global prefix is exported for
 * the same reason: it is part of every path in the document, and a divergence
 * there regenerates a client that calls the wrong URLs.
 *
 * `openapi-document.contract.spec.ts` builds the document through this function
 * and asserts the invariants a generator relies on.
 */

/** Every route is mounted under this, except the health probes. */
export const GLOBAL_PREFIX = 'v1';
export const GLOBAL_PREFIX_EXCLUDE = ['health/live', 'health/ready'];

/**
 * Security scheme names. The cookie scheme MUST be the string controllers pass
 * to `@ApiCookieAuth(...)`: `DocumentBuilder.addCookieAuth` registers the
 * scheme under its third argument, not under the cookie name.
 */
export const SESSION_SECURITY_SCHEME = 'session';
export const API_KEY_SECURITY_SCHEME = 'apiKey';

export function buildOpenApiDocument(app: INestApplication): OpenAPIObject {
  const config = new DocumentBuilder()
    .setTitle('HookuBit Control API')
    .setDescription('Control plane for the webhook delivery platform.')
    .setVersion('1.0')
    .addBearerAuth({ type: 'http', scheme: 'bearer' }, API_KEY_SECURITY_SCHEME)
    .addCookieAuth(SESSION_SECURITY_SCHEME, { type: 'apiKey', in: 'cookie' }, SESSION_SECURITY_SCHEME)
    .build();

  // Every 4xx/5xx response gets the error envelope attached here rather than
  // at 150 decorator sites, most of which are generated by shared
  // authorization decorators and have no hand-written site to edit. See
  // openapi-errors.ts.
  return attachErrorResponses(SwaggerModule.createDocument(app, config));
}
