// Package worker is the delivery stage of the data plane: it leases deliveries,
// signs the exact event bytes, performs the outbound HTTP call through
// internal/egress and advances the delivery state machine (ARCHITECTURE.md
// 19-26, 31, 33, 56, 57).
//
// Everything here assumes at-least-once delivery. A worker that dies after the
// HTTP response but before its database write leaves the delivery leased; the
// lease lapses, another worker reclaims it, and the endpoint receives the
// webhook a second time carrying the SAME Webhook-Delivery-Id. That header is
// the contract that makes the duplicate detectable, and it is why no part of
// this package promises exactly-once (ARCHITECTURE.md 20, engineering rule 31).
package worker

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// The envelope written by the control plane's CryptoService
// (apps/control-api/src/common/crypto.service.ts):
//
//	v1.<kid>.<iv>.<tag>.<ciphertext>
//
// every part except the key id base64url encoded, AES-256-GCM, with additional
// authenticated data binding the ciphertext to the row it belongs to.
//
// This is the highest-risk interop surface in the platform: a mismatch of a
// single byte in the AAD makes every decrypt fail authentication, and it fails
// identically to a wrong key, so it is easy to misdiagnose as configuration.
// crypto_interop_test.go pins both halves against fixtures generated by the
// TypeScript implementation itself - see testdata/README.
const (
	envelopeVersion = "v1"
	keyBytes        = 32
	ivBytes         = 12
	tagBytes        = 16
)

// SecretsTable is the physical table name that appears in the AAD. It must
// equal SECRETS_TABLE in endpoint-secrets.service.ts and the @@map in
// schema.prisma; the three are one string in three languages.
const SecretsTable = "endpoint_secrets"

// kidPattern mirrors KID_PATTERN in crypto.service.ts. The dot is the envelope
// separator, so it cannot appear in a key id.
var kidPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{1,16}$`)

var (
	// ErrMalformedCiphertext covers every structural rejection of an envelope.
	// It never names the key, only what was wrong with the envelope.
	ErrMalformedCiphertext = errors.New("worker: malformed ciphertext")

	// ErrNoKeyForKID means the envelope names a key this process does not
	// hold. That is a deployment problem - a key retired here but not there -
	// and the error names the kid so an operator can fix it.
	ErrNoKeyForKID = errors.New("worker: no encryption key configured for key id")

	// ErrDecrypt is an authentication failure: wrong key, tampered ciphertext,
	// or - the likely one - an AAD that does not match the row the ciphertext
	// was written for.
	ErrDecrypt = errors.New("worker: ciphertext failed authentication")
)

// EncryptionContext is what the ciphertext is bound to, byte for byte identical
// to the TypeScript EncryptionContext.
//
// The TS side builds the AAD as `${table}:${id}:${owner}` in UTF-8, where
// `table` is the physical table, `id` is the primary key of the row holding the
// ciphertext and `owner` is the id of the entity that row hangs off. For a
// signing secret that is (endpoint_secrets, endpoint_secrets.id,
// endpoint_secrets.endpoint_id).
//
// The owner half is not decoration. Without it, anyone with database write
// access could re-point a secret row's endpoint_id and have the platform sign
// another endpoint's traffic with a secret they control; with it, re-pointing
// the row makes the ciphertext undecryptable. Do not "helpfully" fall back to a
// shorter AAD when a field is missing - that is the downgrade path the control
// plane deliberately deleted.
type EncryptionContext struct {
	Table string
	ID    string
	Owner string
}

// AAD returns the additional authenticated data bytes. All three fields are
// required; an unbound ciphertext is the hole the binding exists to close.
func (c EncryptionContext) AAD() ([]byte, error) {
	if c.Table == "" || c.ID == "" || c.Owner == "" {
		return nil, fmt.Errorf("%w: encryption context requires a table, a row id and an owner id", ErrMalformedCiphertext)
	}
	return []byte(c.Table + ":" + c.ID + ":" + c.Owner), nil
}

// SecretContext builds the context for one endpoint_secrets row.
func SecretContext(secretID, endpointID string) EncryptionContext {
	return EncryptionContext{Table: SecretsTable, ID: secretID, Owner: endpointID}
}

// Keyring holds every key accepted for decryption, by key id. The data plane
// never encrypts, so unlike the control plane it has no notion of a primary
// key beyond knowing which id it was handed.
type Keyring struct {
	primaryKID string
	byKID      map[string][]byte
}

// ParseKeyring builds the decryption keyring from the same three environment
// values the control plane reads: ENCRYPTION_KEY (base64, 32 bytes),
// ENCRYPTION_KEY_ID (default "k1") and ENCRYPTION_KEYS_RETIRED (a
// comma-separated list of "<kid>:<base64 key>").
//
// A duplicate key id is an error rather than a silent shadow, exactly as in the
// control plane: which key wins would otherwise depend on parse order, and that
// is a bug that only ever surfaces during a rotation.
func ParseKeyring(primaryKey, primaryKID, retired string) (*Keyring, error) {
	if primaryKID == "" {
		primaryKID = "k1"
	}
	if !kidPattern.MatchString(primaryKID) {
		return nil, fmt.Errorf("ENCRYPTION_KEY_ID must match %s (got %q)", kidPattern, primaryKID)
	}
	key, err := decodeKey(primaryKey, "ENCRYPTION_KEY")
	if err != nil {
		return nil, err
	}

	ring := &Keyring{primaryKID: primaryKID, byKID: map[string][]byte{primaryKID: key}}
	for _, entry := range strings.Split(retired, ",") {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		sep := strings.Index(entry, ":")
		if sep < 1 {
			return nil, fmt.Errorf(`ENCRYPTION_KEYS_RETIRED entries must be "<kid>:<base64key>"`)
		}
		kid := entry[:sep]
		if !kidPattern.MatchString(kid) {
			return nil, fmt.Errorf("ENCRYPTION_KEYS_RETIRED key id must match %s (got %q)", kidPattern, kid)
		}
		if _, exists := ring.byKID[kid]; exists {
			return nil, fmt.Errorf("duplicate encryption key id %q", kid)
		}
		retiredKey, err := decodeKey(entry[sep+1:], "ENCRYPTION_KEYS_RETIRED["+kid+"]")
		if err != nil {
			return nil, err
		}
		ring.byKID[kid] = retiredKey
	}
	return ring, nil
}

// KeyIDs reports the key ids accepted for decryption, for a readiness probe or
// a startup log. It never exposes key material.
func (k *Keyring) KeyIDs() []string {
	ids := make([]string, 0, len(k.byKID))
	for kid := range k.byKID {
		ids = append(ids, kid)
	}
	return ids
}

// PrimaryKeyID reports the key id this process was configured with.
func (k *Keyring) PrimaryKeyID() string { return k.primaryKID }

// Decrypt opens one envelope. The five-part form is the only accepted one; the
// control plane deleted its four-part legacy branch because that branch
// decrypted with the row binding switched off, which is precisely the
// cross-row move the AAD exists to prevent. Do not reintroduce it here.
func (k *Keyring) Decrypt(envelope string, ctx EncryptionContext) (string, error) {
	parts := strings.Split(envelope, ".")
	if len(parts) != 5 {
		return "", fmt.Errorf("%w: expected 5 dot-separated parts, got %d", ErrMalformedCiphertext, len(parts))
	}
	version, kid, ivPart, tagPart, dataPart := parts[0], parts[1], parts[2], parts[3], parts[4]
	if version != envelopeVersion {
		return "", fmt.Errorf("%w: unknown envelope version %q", ErrMalformedCiphertext, version)
	}
	if kid == "" || ivPart == "" || tagPart == "" || dataPart == "" {
		return "", fmt.Errorf("%w: empty envelope part", ErrMalformedCiphertext)
	}

	key, ok := k.byKID[kid]
	if !ok {
		// Name the kid, never the key: an operator needs to know WHICH key is
		// missing from the ring to fix the deployment.
		return "", fmt.Errorf("%w %q", ErrNoKeyForKID, kid)
	}

	iv, err := decodeB64URL(ivPart)
	if err != nil || len(iv) != ivBytes {
		return "", fmt.Errorf("%w: malformed iv", ErrMalformedCiphertext)
	}
	tag, err := decodeB64URL(tagPart)
	if err != nil || len(tag) != tagBytes {
		return "", fmt.Errorf("%w: malformed auth tag", ErrMalformedCiphertext)
	}
	ciphertext, err := decodeB64URL(dataPart)
	if err != nil {
		return "", fmt.Errorf("%w: malformed ciphertext body", ErrMalformedCiphertext)
	}

	aad, err := ctx.AAD()
	if err != nil {
		return "", err
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrDecrypt, err)
	}
	aead, err := cipher.NewGCMWithNonceSize(block, ivBytes)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrDecrypt, err)
	}
	// Node keeps the tag separate; Go's AEAD expects it appended to the
	// ciphertext. Concatenating here is the whole of the difference.
	sealed := make([]byte, 0, len(ciphertext)+len(tag))
	sealed = append(sealed, ciphertext...)
	sealed = append(sealed, tag...)

	plaintext, err := aead.Open(nil, iv, sealed, aad)
	if err != nil {
		// Deliberately vague to the caller and deliberately specific in the
		// hint: the overwhelmingly likely cause is an AAD that does not match
		// the row, not a corrupt ciphertext.
		return "", fmt.Errorf("%w (key id %q, aad %q)", ErrDecrypt, kid, string(aad))
	}
	return string(plaintext), nil
}

// decodeKey accepts the same base64 forms Node's Buffer.from(v, 'base64')
// does, and insists on exactly 32 bytes.
func decodeKey(value, label string) ([]byte, error) {
	if strings.TrimSpace(value) == "" {
		return nil, fmt.Errorf("%s is required", label)
	}
	key, err := decodeB64Any(value)
	if err != nil {
		return nil, fmt.Errorf("%s must be base64-encoded: %w", label, err)
	}
	if len(key) != keyBytes {
		return nil, fmt.Errorf("%s must be %d bytes, base64-encoded (got %d)", label, keyBytes, len(key))
	}
	return key, nil
}

// decodeB64URL decodes an envelope part. Node writes base64url without
// padding, but Buffer.from(x, 'base64url') accepts padding, so accept both
// rather than making a padded envelope from some future writer undecryptable.
func decodeB64URL(s string) ([]byte, error) {
	return base64.RawURLEncoding.DecodeString(strings.TrimRight(s, "="))
}

// decodeB64Any accepts standard or URL-safe base64, padded or not - matching
// Node's permissive decoder, so a key pasted from either alphabet works.
func decodeB64Any(s string) ([]byte, error) {
	s = strings.TrimSpace(s)
	trimmed := strings.TrimRight(s, "=")
	if b, err := base64.RawStdEncoding.DecodeString(trimmed); err == nil {
		return b, nil
	}
	return base64.RawURLEncoding.DecodeString(trimmed)
}
