package worker

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// This is THE cross-language test. Endpoint signing secrets are written by the
// NestJS control plane and read here; if the two implementations disagree by
// one byte of additional authenticated data, every decrypt fails
// authentication and every delivery to every endpoint fails to sign - and the
// failure looks identical to a misconfigured key, which is how it stays
// misdiagnosed for a day.
//
// The fixture is generated by the control plane's own compiled CryptoService,
// not reconstructed from its source. See testdata/README.md.

type interopFixture struct {
	PrimaryKeyB64 string `json:"primary_key_b64"`
	RetiredKeyB64 string `json:"retired_key_b64"`
	Vectors       []struct {
		KID     string `json:"kid"`
		Context struct {
			Table string `json:"table"`
			ID    string `json:"id"`
			Owner string `json:"owner"`
		} `json:"context"`
		Plaintext string `json:"plaintext"`
		Envelope  string `json:"envelope"`
	} `json:"vectors"`
}

func loadInteropFixture(t *testing.T) interopFixture {
	t.Helper()
	raw, err := os.ReadFile("testdata/crypto_interop.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var fx interopFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(fx.Vectors) < 2 {
		t.Fatalf("fixture must cover the primary and a retired key; got %d vectors", len(fx.Vectors))
	}
	return fx
}

func interopKeyring(t *testing.T, fx interopFixture) *Keyring {
	t.Helper()
	ring, err := ParseKeyring(fx.PrimaryKeyB64, "k1", "k0:"+fx.RetiredKeyB64)
	if err != nil {
		t.Fatalf("build keyring: %v", err)
	}
	return ring
}

func TestDecryptsTypeScriptEnvelopes(t *testing.T) {
	fx := loadInteropFixture(t)
	ring := interopKeyring(t, fx)

	for _, v := range fx.Vectors {
		v := v
		t.Run(v.KID, func(t *testing.T) {
			ctx := EncryptionContext{Table: v.Context.Table, ID: v.Context.ID, Owner: v.Context.Owner}
			got, err := ring.Decrypt(v.Envelope, ctx)
			if err != nil {
				t.Fatalf("decrypt TypeScript envelope: %v", err)
			}
			if got != v.Plaintext {
				t.Fatalf("plaintext mismatch: got %q want %q", got, v.Plaintext)
			}
		})
	}
}

// The AAD is the part most likely to be silently wrong, so it is asserted from
// three directions: the exact bytes, and both ways a real ciphertext can be
// moved in the database.
func TestAADIsTableRowOwnerSeparatedByColons(t *testing.T) {
	aad, err := SecretContext("eps_1", "ep_2").AAD()
	if err != nil {
		t.Fatalf("aad: %v", err)
	}
	if want := "endpoint_secrets:eps_1:ep_2"; string(aad) != want {
		t.Fatalf("AAD = %q, want %q (must match `${table}:${id}:${owner}` in crypto.service.ts)", aad, want)
	}
}

func TestDecryptRejectsCiphertextMovedToAnotherRow(t *testing.T) {
	fx := loadInteropFixture(t)
	ring := interopKeyring(t, fx)
	v := fx.Vectors[0]

	// Same endpoint, different secret row: the copy-the-ciphertext-elsewhere move.
	_, err := ring.Decrypt(v.Envelope, EncryptionContext{
		Table: v.Context.Table, ID: "eps_someone_elses_row", Owner: v.Context.Owner,
	})
	if err == nil {
		t.Fatal("ciphertext decrypted under a different row id; the AAD binding is not effective")
	}

	// Same row, re-pointed at another endpoint: the UPDATE-the-owner move that
	// the `owner` field was added to close.
	_, err = ring.Decrypt(v.Envelope, EncryptionContext{
		Table: v.Context.Table, ID: v.Context.ID, Owner: "ep_attacker_controlled",
	})
	if err == nil {
		t.Fatal("ciphertext decrypted under a different endpoint; re-pointing endpoint_id is not detected")
	}
}

func TestDecryptRejectsTamperedCiphertext(t *testing.T) {
	fx := loadInteropFixture(t)
	ring := interopKeyring(t, fx)
	v := fx.Vectors[0]
	ctx := EncryptionContext{Table: v.Context.Table, ID: v.Context.ID, Owner: v.Context.Owner}

	parts := strings.Split(v.Envelope, ".")
	body := []byte(parts[4])
	body[0] ^= 0x01 // flip a base64url character
	parts[4] = string(body)
	if _, err := ring.Decrypt(strings.Join(parts, "."), ctx); err == nil {
		t.Fatal("tampered ciphertext authenticated")
	}
}

func TestDecryptRejectsUnknownKeyIDByName(t *testing.T) {
	fx := loadInteropFixture(t)
	ring := interopKeyring(t, fx)
	v := fx.Vectors[0]
	parts := strings.Split(v.Envelope, ".")
	parts[1] = "k99"

	_, err := ring.Decrypt(strings.Join(parts, "."), EncryptionContext{
		Table: v.Context.Table, ID: v.Context.ID, Owner: v.Context.Owner,
	})
	if err == nil {
		t.Fatal("envelope naming an unconfigured key id decrypted")
	}
	if !strings.Contains(err.Error(), "k99") {
		t.Fatalf("error must name the missing key id so an operator can fix the deployment: %v", err)
	}
	if strings.Contains(err.Error(), fx.PrimaryKeyB64) || strings.Contains(err.Error(), fx.RetiredKeyB64) {
		t.Fatal("error leaked key material")
	}
}

// The four-part envelope was a downgrade path in the control plane: it
// decrypted with the row binding switched off. It is gone there and must never
// be accepted here.
func TestDecryptRejectsLegacyFourPartEnvelope(t *testing.T) {
	fx := loadInteropFixture(t)
	ring := interopKeyring(t, fx)
	v := fx.Vectors[0]
	parts := strings.Split(v.Envelope, ".")
	legacy := strings.Join([]string{parts[0], parts[2], parts[3], parts[4]}, ".")

	if _, err := ring.Decrypt(legacy, EncryptionContext{
		Table: v.Context.Table, ID: v.Context.ID, Owner: v.Context.Owner,
	}); err == nil {
		t.Fatal("four-part legacy envelope accepted; that path decrypts without the row binding")
	}
}

func TestParseKeyringValidatesKeys(t *testing.T) {
	fx := loadInteropFixture(t)

	if _, err := ParseKeyring("", "k1", ""); err == nil {
		t.Fatal("empty ENCRYPTION_KEY accepted")
	}
	if _, err := ParseKeyring("c2hvcnQ=", "k1", ""); err == nil {
		t.Fatal("a key that is not 32 bytes was accepted")
	}
	if _, err := ParseKeyring(fx.PrimaryKeyB64, "has.a.dot", ""); err == nil {
		t.Fatal("a key id containing the envelope separator was accepted")
	}
	if _, err := ParseKeyring(fx.PrimaryKeyB64, "k1", "k1:"+fx.RetiredKeyB64); err == nil {
		t.Fatal("a duplicate key id was accepted; which key wins would depend on parse order")
	}
	if _, err := ParseKeyring(fx.PrimaryKeyB64, "k1", "no-colon"); err == nil {
		t.Fatal("a malformed retired entry was accepted")
	}

	ring, err := ParseKeyring(fx.PrimaryKeyB64, "", "")
	if err != nil {
		t.Fatalf("default key id: %v", err)
	}
	if ring.PrimaryKeyID() != "k1" {
		t.Fatalf("default key id = %q, want k1 (must match crypto.service.ts)", ring.PrimaryKeyID())
	}
}
